// Server-side counterpart to the client's useMarketAlert hook. The client
// version had every open tab independently re-scan ~24 symbols × 4
// timeframes every 15 minutes AND could only notify while that tab was
// open — this runs the scan once, centrally, and pushes every approved user,
// which is both more reliable (works app-closed) and cheaper (one scan
// instead of one per open tab).
import { getDb } from "./db.server";
import { SYMBOLS } from "./deriv";
import { fetchCandlesServer } from "./deriv.server";
import { analyzeSymbolCore } from "./signal-core";
import { mapWithConcurrency } from "./utils";

const CHECK_INTERVAL_MS = 15 * 60_000;
const MIN_CONFIDENCE = 75;
const MIN_AGREEMENT = 3;
const REALERT_COOLDOWN_MS = 30 * 60_000;

const lastAlertedAt = new Map<string, number>(); // deriv symbol -> timestamp

async function scanOnce(): Promise<void> {
  // Synthetic indices (R_*, 1HZ*…) are RNG-generated by Deriv — no indicator
  // has a real edge on them, same exclusion as the bot engine and the old
  // client scanner.
  const tradeable = SYMBOLS.filter((s) => s.market !== "synthetic");
  const now = Date.now();

  const hits = await mapWithConcurrency(tradeable, 6, async (sym) => {
    try {
      const { analysis } = await analyzeSymbolCore(sym.deriv, fetchCandlesServer);
      if (!analysis.direction) return null;
      if (analysis.confidence < MIN_CONFIDENCE) return null;
      if (analysis.agreement < MIN_AGREEMENT) return null;

      const last = lastAlertedAt.get(sym.deriv) ?? 0;
      if (now - last < REALERT_COOLDOWN_MS) return null;

      return { sym, analysis };
    } catch (e) {
      console.error(`[signal-scan] Échec pour ${sym.deriv}:`, (e as Error).message);
      return null;
    }
  });

  const fresh = hits.filter((h): h is NonNullable<typeof h> => !!h);
  if (!fresh.length) return;

  const db = getDb();
  const users = db.prepare("SELECT id FROM users WHERE status = 'approved'").all() as { id: number }[];
  if (!users.length) return;
  const { sendPushToUser } = await import("./push.server");

  for (const { sym, analysis } of fresh) {
    lastAlertedAt.set(sym.deriv, now);
    const direction = analysis.direction === "CALL" ? "BUY" : "SELL";
    await Promise.allSettled(
      users.map((u) =>
        sendPushToUser(u.id, {
          title: `Au Pluriel — Signal fort sur ${sym.label}`,
          body: `${direction} · Confiance ${Math.round(analysis.confidence)}% · ${analysis.agreement}/4 TF · Marché favorable`,
          url: "/signals",
        }),
      ),
    );
  }
}

export function startSignalScanScheduler(): void {
  setTimeout(() => scanOnce().catch((e) => console.error("[signal-scan] Scan échoué:", (e as Error).message)), 30_000);
  setInterval(() => scanOnce().catch((e) => console.error("[signal-scan] Scan échoué:", (e as Error).message)), CHECK_INTERVAL_MS);
  console.log("[signal-scan] Scheduler démarré.");
}
