import { useEffect, useRef, useState } from "react";
import { fetchCandles, GRANULARITY, SYMBOLS } from "@/lib/deriv";
import { generateSignal } from "@/lib/indicators";
import { mapWithConcurrency } from "@/lib/utils";

export interface MarketAlert {
  symbol: string;
  label: string;
  direction: "BUY" | "SELL";
  confidence: number;
  agreement: number;
  time: number;
}

const TIMEFRAMES = ["5m", "15m", "1H", "4H"] as const;
const CHECK_INTERVAL_MS = 15 * 60_000; // every 15 minutes
const ALERT_STORAGE_KEY = "lio23.last_alert_times";
const MIN_CONFIDENCE = 75;
const MIN_AGREEMENT = 3;

function loadLastAlertTimes(): Record<string, number> {
  try {
    return JSON.parse(localStorage.getItem(ALERT_STORAGE_KEY) ?? "{}");
  } catch {
    return {};
  }
}

function saveLastAlertTimes(times: Record<string, number>) {
  try {
    localStorage.setItem(ALERT_STORAGE_KEY, JSON.stringify(times));
  } catch {}
}

async function requestNotificationPermission(): Promise<boolean> {
  if (typeof window === "undefined" || !("Notification" in window)) return false;
  if (Notification.permission === "granted") return true;
  if (Notification.permission === "denied") return false;
  const result = await Notification.requestPermission();
  return result === "granted";
}

function sendBrowserNotification(alert: MarketAlert) {
  if (typeof window === "undefined" || Notification.permission !== "granted") return;
  const n = new Notification(`Au Pluriel — Signal fort sur ${alert.label}`, {
    body: `${alert.direction} · Confiance ${alert.confidence}% · ${alert.agreement}/4 TF · Marché favorable`,
    icon: "/favicon.ico",
    tag: `lio23-${alert.symbol}`, // replace previous for same symbol
    requireInteraction: false,
  });
  // Auto-close after 8s
  setTimeout(() => n.close(), 8000);
}

async function analyzeSymbol(
  deriv: string,
): Promise<{ direction: "BUY" | "SELL" | null; confidence: number; agreement: number }> {
  const votes: string[] = [];
  let totalConf = 0;

  for (const tf of TIMEFRAMES) {
    try {
      const candles = await fetchCandles(deriv, GRANULARITY[tf], 250);
      if (!candles.length) continue;
      const sig = generateSignal(candles);
      if (sig.direction === "HOLD" || sig.triggers[0] === "insufficient-data") continue;
      votes.push(sig.direction);
      totalConf += sig.confidence;
    } catch {}
  }

  if (!votes.length) return { direction: null, confidence: 0, agreement: 0 };
  const buys = votes.filter((v) => v === "BUY").length;
  const sells = votes.filter((v) => v === "SELL").length;
  const avgConf = totalConf / votes.length;

  if (buys > sells) return { direction: "BUY", confidence: avgConf, agreement: buys };
  if (sells > buys) return { direction: "SELL", confidence: avgConf, agreement: sells };
  return { direction: null, confidence: avgConf, agreement: 0 };
}

export function useMarketAlert(enabled = true) {
  const [activeAlerts, setActiveAlerts] = useState<MarketAlert[]>([]);
  const [notifPermission, setNotifPermission] = useState<NotificationPermission>("default");
  const lastAlertTimesRef = useRef<Record<string, number>>(loadLastAlertTimes());

  // Read permission status
  useEffect(() => {
    if (typeof window !== "undefined" && "Notification" in window) {
      setNotifPermission(Notification.permission);
    }
  }, []);

  async function requestPermission() {
    const granted = await requestNotificationPermission();
    if (typeof window !== "undefined" && "Notification" in window) {
      setNotifPermission(Notification.permission);
    }
    return granted;
  }

  async function checkSignals() {
    const now = Date.now();
    const newAlerts: MarketAlert[] = [];

    // Synthetic indices (R_*, 1HZ*…) are RNG-generated by Deriv — no indicator
    // has a real edge on them (see DEFAULT_CONFIG.symbols in signal-core.ts).
    // Alerting on one would point the user at a "signal" the bot itself would
    // never trade.
    const tradeableSymbols = SYMBOLS.filter((s) => s.market !== "synthetic");

    // Concurrency-capped instead of sequential: ~28 symbols × 4 timeframes each
    // awaited one at a time could take minutes; this bounds it without
    // hammering the shared Deriv connection.
    const analyzed = await mapWithConcurrency(tradeableSymbols, 6, async (sym) => {
      try {
        return { sym, result: await analyzeSymbol(sym.deriv) };
      } catch {
        return null;
      }
    });

    for (const entry of analyzed) {
      if (!entry) continue;
      const { sym, result } = entry;
      if (!result.direction) continue;
      if (result.confidence < MIN_CONFIDENCE) continue;
      if (result.agreement < MIN_AGREEMENT) continue;

      const alert: MarketAlert = {
        symbol: sym.deriv,
        label: sym.label,
        direction: result.direction,
        confidence: Math.round(result.confidence),
        agreement: result.agreement,
        time: now,
      };
      newAlerts.push(alert);

      // Only send notification if we haven't alerted on this symbol in the last 30 min
      const lastTime = lastAlertTimesRef.current[sym.deriv] ?? 0;
      if (now - lastTime > 30 * 60_000) {
        sendBrowserNotification(alert);
        lastAlertTimesRef.current[sym.deriv] = now;
        saveLastAlertTimes(lastAlertTimesRef.current);
      }
    }

    setActiveAlerts(newAlerts);
  }

  useEffect(() => {
    if (!enabled) {
      setActiveAlerts([]);
      return;
    }

    // Delay the first heavy scan so it doesn't compete with initial page render
    const warmup = setTimeout(checkSignals, 8000);
    const id = setInterval(checkSignals, CHECK_INTERVAL_MS);
    return () => { clearTimeout(warmup); clearInterval(id); };
  }, [enabled]);

  return { activeAlerts, notifPermission, requestPermission };
}
