/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MessengerRouteImport } from './routes/messenger'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CarnetDeNotesRouteImport } from './routes/carnet-de-notes'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as AutotraderRouteImport } from './routes/autotrader'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiTradesRouteImport } from './routes/api/trades'
import { Route as ApiStrategiesRouteImport } from './routes/api/strategies'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiPushRouteImport } from './routes/api/push'
import { Route as ApiPresenceRouteImport } from './routes/api/presence'
import { Route as ApiNotesRouteImport } from './routes/api/notes'
import { Route as ApiLearningRouteImport } from './routes/api/learning'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiDerivSessionRouteImport } from './routes/api/deriv-session'
import { Route as ApiBotRouteImport } from './routes/api/bot'
import { Route as ApiAutoBacktestRouteImport } from './routes/api/auto-backtest'
import { Route as ApiAlertsRouteImport } from './routes/api/alerts'
import { Route as ApiChatUsersRouteImport } from './routes/api/chat/users'
import { Route as ApiChatTypingRouteImport } from './routes/api/chat/typing'
import { Route as ApiChatReactionsRouteImport } from './routes/api/chat/reactions'
import { Route as ApiChatMessagesRouteImport } from './routes/api/chat/messages'
import { Route as ApiChatGroupsRouteImport } from './routes/api/chat/groups'
import { Route as ApiAuthVerifyEmailRouteImport } from './routes/api/auth/verify-email'
import { Route as ApiAuthResetPasswordRouteImport } from './routes/api/auth/reset-password'
import { Route as ApiAuthResendVerificationRouteImport } from './routes/api/auth/resend-verification'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthForgotPasswordRouteImport } from './routes/api/auth/forgot-password'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminUserConfigRouteImport } from './routes/api/admin/user-config'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminInvitesRouteImport } from './routes/api/admin/invites'
import { Route as ApiAdminHealthRouteImport } from './routes/api/admin/health'
import { Route as ApiAdminChangelogRouteImport } from './routes/api/admin/changelog'
import { Route as ApiAdminBotRouteImport } from './routes/api/admin/bot'
import { Route as ApiChatGroupsMembersRouteImport } from './routes/api/chat/groups/members'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MessengerRoute = MessengerRouteImport.update({
  id: '/messenger',
  path: '/messenger',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CarnetDeNotesRoute = CarnetDeNotesRouteImport.update({
  id: '/carnet-de-notes',
  path: '/carnet-de-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AutotraderRoute = AutotraderRouteImport.update({
  id: '/autotrader',
  path: '/autotrader',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradesRoute = ApiTradesRouteImport.update({
  id: '/api/trades',
  path: '/api/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStrategiesRoute = ApiStrategiesRouteImport.update({
  id: '/api/strategies',
  path: '/api/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushRoute = ApiPushRouteImport.update({
  id: '/api/push',
  path: '/api/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPresenceRoute = ApiPresenceRouteImport.update({
  id: '/api/presence',
  path: '/api/presence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesRoute = ApiNotesRouteImport.update({
  id: '/api/notes',
  path: '/api/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningRoute = ApiLearningRouteImport.update({
  id: '/api/learning',
  path: '/api/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDerivSessionRoute = ApiDerivSessionRouteImport.update({
  id: '/api/deriv-session',
  path: '/api/deriv-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotRoute = ApiBotRouteImport.update({
  id: '/api/bot',
  path: '/api/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoBacktestRoute = ApiAutoBacktestRouteImport.update({
  id: '/api/auto-backtest',
  path: '/api/auto-backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsRoute = ApiAlertsRouteImport.update({
  id: '/api/alerts',
  path: '/api/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatUsersRoute = ApiChatUsersRouteImport.update({
  id: '/api/chat/users',
  path: '/api/chat/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatTypingRoute = ApiChatTypingRouteImport.update({
  id: '/api/chat/typing',
  path: '/api/chat/typing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatReactionsRoute = ApiChatReactionsRouteImport.update({
  id: '/api/chat/reactions',
  path: '/api/chat/reactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatMessagesRoute = ApiChatMessagesRouteImport.update({
  id: '/api/chat/messages',
  path: '/api/chat/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatGroupsRoute = ApiChatGroupsRouteImport.update({
  id: '/api/chat/groups',
  path: '/api/chat/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyEmailRoute = ApiAuthVerifyEmailRouteImport.update({
  id: '/api/auth/verify-email',
  path: '/api/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetPasswordRoute = ApiAuthResetPasswordRouteImport.update({
  id: '/api/auth/reset-password',
  path: '/api/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResendVerificationRoute =
  ApiAuthResendVerificationRouteImport.update({
    id: '/api/auth/resend-verification',
    path: '/api/auth/resend-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthForgotPasswordRoute = ApiAuthForgotPasswordRouteImport.update({
  id: '/api/auth/forgot-password',
  path: '/api/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUserConfigRoute = ApiAdminUserConfigRouteImport.update({
  id: '/api/admin/user-config',
  path: '/api/admin/user-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInvitesRoute = ApiAdminInvitesRouteImport.update({
  id: '/api/admin/invites',
  path: '/api/admin/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminHealthRoute = ApiAdminHealthRouteImport.update({
  id: '/api/admin/health',
  path: '/api/admin/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminChangelogRoute = ApiAdminChangelogRouteImport.update({
  id: '/api/admin/changelog',
  path: '/api/admin/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBotRoute = ApiAdminBotRouteImport.update({
  id: '/api/admin/bot',
  path: '/api/admin/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatGroupsMembersRoute = ApiChatGroupsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ApiChatGroupsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/autotrader': typeof AutotraderRoute
  '/backtest': typeof BacktestRoute
  '/carnet-de-notes': typeof CarnetDeNotesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/messenger': typeof MessengerRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/strategies': typeof StrategiesRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/auto-backtest': typeof ApiAutoBacktestRoute
  '/api/bot': typeof ApiBotRoute
  '/api/deriv-session': typeof ApiDerivSessionRoute
  '/api/health': typeof ApiHealthRoute
  '/api/learning': typeof ApiLearningRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/presence': typeof ApiPresenceRoute
  '/api/push': typeof ApiPushRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/strategies': typeof ApiStrategiesRoute
  '/api/trades': typeof ApiTradesRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/admin/bot': typeof ApiAdminBotRoute
  '/api/admin/changelog': typeof ApiAdminChangelogRoute
  '/api/admin/health': typeof ApiAdminHealthRoute
  '/api/admin/invites': typeof ApiAdminInvitesRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/user-config': typeof ApiAdminUserConfigRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/resend-verification': typeof ApiAuthResendVerificationRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/chat/groups': typeof ApiChatGroupsRouteWithChildren
  '/api/chat/messages': typeof ApiChatMessagesRoute
  '/api/chat/reactions': typeof ApiChatReactionsRoute
  '/api/chat/typing': typeof ApiChatTypingRoute
  '/api/chat/users': typeof ApiChatUsersRoute
  '/api/chat/groups/members': typeof ApiChatGroupsMembersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/autotrader': typeof AutotraderRoute
  '/backtest': typeof BacktestRoute
  '/carnet-de-notes': typeof CarnetDeNotesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/messenger': typeof MessengerRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/strategies': typeof StrategiesRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/auto-backtest': typeof ApiAutoBacktestRoute
  '/api/bot': typeof ApiBotRoute
  '/api/deriv-session': typeof ApiDerivSessionRoute
  '/api/health': typeof ApiHealthRoute
  '/api/learning': typeof ApiLearningRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/presence': typeof ApiPresenceRoute
  '/api/push': typeof ApiPushRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/strategies': typeof ApiStrategiesRoute
  '/api/trades': typeof ApiTradesRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/admin/bot': typeof ApiAdminBotRoute
  '/api/admin/changelog': typeof ApiAdminChangelogRoute
  '/api/admin/health': typeof ApiAdminHealthRoute
  '/api/admin/invites': typeof ApiAdminInvitesRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/user-config': typeof ApiAdminUserConfigRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/resend-verification': typeof ApiAuthResendVerificationRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/chat/groups': typeof ApiChatGroupsRouteWithChildren
  '/api/chat/messages': typeof ApiChatMessagesRoute
  '/api/chat/reactions': typeof ApiChatReactionsRoute
  '/api/chat/typing': typeof ApiChatTypingRoute
  '/api/chat/users': typeof ApiChatUsersRoute
  '/api/chat/groups/members': typeof ApiChatGroupsMembersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/autotrader': typeof AutotraderRoute
  '/backtest': typeof BacktestRoute
  '/carnet-de-notes': typeof CarnetDeNotesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/messenger': typeof MessengerRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/strategies': typeof StrategiesRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/auto-backtest': typeof ApiAutoBacktestRoute
  '/api/bot': typeof ApiBotRoute
  '/api/deriv-session': typeof ApiDerivSessionRoute
  '/api/health': typeof ApiHealthRoute
  '/api/learning': typeof ApiLearningRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/presence': typeof ApiPresenceRoute
  '/api/push': typeof ApiPushRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/strategies': typeof ApiStrategiesRoute
  '/api/trades': typeof ApiTradesRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/admin/bot': typeof ApiAdminBotRoute
  '/api/admin/changelog': typeof ApiAdminChangelogRoute
  '/api/admin/health': typeof ApiAdminHealthRoute
  '/api/admin/invites': typeof ApiAdminInvitesRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/user-config': typeof ApiAdminUserConfigRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/resend-verification': typeof ApiAuthResendVerificationRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/chat/groups': typeof ApiChatGroupsRouteWithChildren
  '/api/chat/messages': typeof ApiChatMessagesRoute
  '/api/chat/reactions': typeof ApiChatReactionsRoute
  '/api/chat/typing': typeof ApiChatTypingRoute
  '/api/chat/users': typeof ApiChatUsersRoute
  '/api/chat/groups/members': typeof ApiChatGroupsMembersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/autotrader'
    | '/backtest'
    | '/carnet-de-notes'
    | '/forgot-password'
    | '/journal'
    | '/login'
    | '/markets'
    | '/messenger'
    | '/portfolio'
    | '/reset-password'
    | '/settings'
    | '/signals'
    | '/strategies'
    | '/verify-email'
    | '/api/alerts'
    | '/api/auto-backtest'
    | '/api/bot'
    | '/api/deriv-session'
    | '/api/health'
    | '/api/learning'
    | '/api/notes'
    | '/api/presence'
    | '/api/push'
    | '/api/settings'
    | '/api/strategies'
    | '/api/trades'
    | '/api/transcribe'
    | '/api/admin/bot'
    | '/api/admin/changelog'
    | '/api/admin/health'
    | '/api/admin/invites'
    | '/api/admin/stats'
    | '/api/admin/user-config'
    | '/api/admin/users'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/resend-verification'
    | '/api/auth/reset-password'
    | '/api/auth/verify-email'
    | '/api/chat/groups'
    | '/api/chat/messages'
    | '/api/chat/reactions'
    | '/api/chat/typing'
    | '/api/chat/users'
    | '/api/chat/groups/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/autotrader'
    | '/backtest'
    | '/carnet-de-notes'
    | '/forgot-password'
    | '/journal'
    | '/login'
    | '/markets'
    | '/messenger'
    | '/portfolio'
    | '/reset-password'
    | '/settings'
    | '/signals'
    | '/strategies'
    | '/verify-email'
    | '/api/alerts'
    | '/api/auto-backtest'
    | '/api/bot'
    | '/api/deriv-session'
    | '/api/health'
    | '/api/learning'
    | '/api/notes'
    | '/api/presence'
    | '/api/push'
    | '/api/settings'
    | '/api/strategies'
    | '/api/trades'
    | '/api/transcribe'
    | '/api/admin/bot'
    | '/api/admin/changelog'
    | '/api/admin/health'
    | '/api/admin/invites'
    | '/api/admin/stats'
    | '/api/admin/user-config'
    | '/api/admin/users'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/resend-verification'
    | '/api/auth/reset-password'
    | '/api/auth/verify-email'
    | '/api/chat/groups'
    | '/api/chat/messages'
    | '/api/chat/reactions'
    | '/api/chat/typing'
    | '/api/chat/users'
    | '/api/chat/groups/members'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/autotrader'
    | '/backtest'
    | '/carnet-de-notes'
    | '/forgot-password'
    | '/journal'
    | '/login'
    | '/markets'
    | '/messenger'
    | '/portfolio'
    | '/reset-password'
    | '/settings'
    | '/signals'
    | '/strategies'
    | '/verify-email'
    | '/api/alerts'
    | '/api/auto-backtest'
    | '/api/bot'
    | '/api/deriv-session'
    | '/api/health'
    | '/api/learning'
    | '/api/notes'
    | '/api/presence'
    | '/api/push'
    | '/api/settings'
    | '/api/strategies'
    | '/api/trades'
    | '/api/transcribe'
    | '/api/admin/bot'
    | '/api/admin/changelog'
    | '/api/admin/health'
    | '/api/admin/invites'
    | '/api/admin/stats'
    | '/api/admin/user-config'
    | '/api/admin/users'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/resend-verification'
    | '/api/auth/reset-password'
    | '/api/auth/verify-email'
    | '/api/chat/groups'
    | '/api/chat/messages'
    | '/api/chat/reactions'
    | '/api/chat/typing'
    | '/api/chat/users'
    | '/api/chat/groups/members'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  AutotraderRoute: typeof AutotraderRoute
  BacktestRoute: typeof BacktestRoute
  CarnetDeNotesRoute: typeof CarnetDeNotesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  MessengerRoute: typeof MessengerRoute
  PortfolioRoute: typeof PortfolioRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignalsRoute: typeof SignalsRoute
  StrategiesRoute: typeof StrategiesRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiAlertsRoute: typeof ApiAlertsRoute
  ApiAutoBacktestRoute: typeof ApiAutoBacktestRoute
  ApiBotRoute: typeof ApiBotRoute
  ApiDerivSessionRoute: typeof ApiDerivSessionRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLearningRoute: typeof ApiLearningRoute
  ApiNotesRoute: typeof ApiNotesRoute
  ApiPresenceRoute: typeof ApiPresenceRoute
  ApiPushRoute: typeof ApiPushRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiStrategiesRoute: typeof ApiStrategiesRoute
  ApiTradesRoute: typeof ApiTradesRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiAdminBotRoute: typeof ApiAdminBotRoute
  ApiAdminChangelogRoute: typeof ApiAdminChangelogRoute
  ApiAdminHealthRoute: typeof ApiAdminHealthRoute
  ApiAdminInvitesRoute: typeof ApiAdminInvitesRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminUserConfigRoute: typeof ApiAdminUserConfigRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthForgotPasswordRoute: typeof ApiAuthForgotPasswordRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthResendVerificationRoute: typeof ApiAuthResendVerificationRoute
  ApiAuthResetPasswordRoute: typeof ApiAuthResetPasswordRoute
  ApiAuthVerifyEmailRoute: typeof ApiAuthVerifyEmailRoute
  ApiChatGroupsRoute: typeof ApiChatGroupsRouteWithChildren
  ApiChatMessagesRoute: typeof ApiChatMessagesRoute
  ApiChatReactionsRoute: typeof ApiChatReactionsRoute
  ApiChatTypingRoute: typeof ApiChatTypingRoute
  ApiChatUsersRoute: typeof ApiChatUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messenger': {
      id: '/messenger'
      path: '/messenger'
      fullPath: '/messenger'
      preLoaderRoute: typeof MessengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carnet-de-notes': {
      id: '/carnet-de-notes'
      path: '/carnet-de-notes'
      fullPath: '/carnet-de-notes'
      preLoaderRoute: typeof CarnetDeNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autotrader': {
      id: '/autotrader'
      path: '/autotrader'
      fullPath: '/autotrader'
      preLoaderRoute: typeof AutotraderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trades': {
      id: '/api/trades'
      path: '/api/trades'
      fullPath: '/api/trades'
      preLoaderRoute: typeof ApiTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strategies': {
      id: '/api/strategies'
      path: '/api/strategies'
      fullPath: '/api/strategies'
      preLoaderRoute: typeof ApiStrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push': {
      id: '/api/push'
      path: '/api/push'
      fullPath: '/api/push'
      preLoaderRoute: typeof ApiPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presence': {
      id: '/api/presence'
      path: '/api/presence'
      fullPath: '/api/presence'
      preLoaderRoute: typeof ApiPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes': {
      id: '/api/notes'
      path: '/api/notes'
      fullPath: '/api/notes'
      preLoaderRoute: typeof ApiNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning': {
      id: '/api/learning'
      path: '/api/learning'
      fullPath: '/api/learning'
      preLoaderRoute: typeof ApiLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deriv-session': {
      id: '/api/deriv-session'
      path: '/api/deriv-session'
      fullPath: '/api/deriv-session'
      preLoaderRoute: typeof ApiDerivSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot': {
      id: '/api/bot'
      path: '/api/bot'
      fullPath: '/api/bot'
      preLoaderRoute: typeof ApiBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auto-backtest': {
      id: '/api/auto-backtest'
      path: '/api/auto-backtest'
      fullPath: '/api/auto-backtest'
      preLoaderRoute: typeof ApiAutoBacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts': {
      id: '/api/alerts'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/users': {
      id: '/api/chat/users'
      path: '/api/chat/users'
      fullPath: '/api/chat/users'
      preLoaderRoute: typeof ApiChatUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/typing': {
      id: '/api/chat/typing'
      path: '/api/chat/typing'
      fullPath: '/api/chat/typing'
      preLoaderRoute: typeof ApiChatTypingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/reactions': {
      id: '/api/chat/reactions'
      path: '/api/chat/reactions'
      fullPath: '/api/chat/reactions'
      preLoaderRoute: typeof ApiChatReactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/messages': {
      id: '/api/chat/messages'
      path: '/api/chat/messages'
      fullPath: '/api/chat/messages'
      preLoaderRoute: typeof ApiChatMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/groups': {
      id: '/api/chat/groups'
      path: '/api/chat/groups'
      fullPath: '/api/chat/groups'
      preLoaderRoute: typeof ApiChatGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify-email': {
      id: '/api/auth/verify-email'
      path: '/api/auth/verify-email'
      fullPath: '/api/auth/verify-email'
      preLoaderRoute: typeof ApiAuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset-password': {
      id: '/api/auth/reset-password'
      path: '/api/auth/reset-password'
      fullPath: '/api/auth/reset-password'
      preLoaderRoute: typeof ApiAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/resend-verification': {
      id: '/api/auth/resend-verification'
      path: '/api/auth/resend-verification'
      fullPath: '/api/auth/resend-verification'
      preLoaderRoute: typeof ApiAuthResendVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/forgot-password': {
      id: '/api/auth/forgot-password'
      path: '/api/auth/forgot-password'
      fullPath: '/api/auth/forgot-password'
      preLoaderRoute: typeof ApiAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/user-config': {
      id: '/api/admin/user-config'
      path: '/api/admin/user-config'
      fullPath: '/api/admin/user-config'
      preLoaderRoute: typeof ApiAdminUserConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/invites': {
      id: '/api/admin/invites'
      path: '/api/admin/invites'
      fullPath: '/api/admin/invites'
      preLoaderRoute: typeof ApiAdminInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/health': {
      id: '/api/admin/health'
      path: '/api/admin/health'
      fullPath: '/api/admin/health'
      preLoaderRoute: typeof ApiAdminHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/changelog': {
      id: '/api/admin/changelog'
      path: '/api/admin/changelog'
      fullPath: '/api/admin/changelog'
      preLoaderRoute: typeof ApiAdminChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bot': {
      id: '/api/admin/bot'
      path: '/api/admin/bot'
      fullPath: '/api/admin/bot'
      preLoaderRoute: typeof ApiAdminBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/groups/members': {
      id: '/api/chat/groups/members'
      path: '/members'
      fullPath: '/api/chat/groups/members'
      preLoaderRoute: typeof ApiChatGroupsMembersRouteImport
      parentRoute: typeof ApiChatGroupsRoute
    }
  }
}

interface ApiChatGroupsRouteChildren {
  ApiChatGroupsMembersRoute: typeof ApiChatGroupsMembersRoute
}

const ApiChatGroupsRouteChildren: ApiChatGroupsRouteChildren = {
  ApiChatGroupsMembersRoute: ApiChatGroupsMembersRoute,
}

const ApiChatGroupsRouteWithChildren = ApiChatGroupsRoute._addFileChildren(
  ApiChatGroupsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  AutotraderRoute: AutotraderRoute,
  BacktestRoute: BacktestRoute,
  CarnetDeNotesRoute: CarnetDeNotesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  MessengerRoute: MessengerRoute,
  PortfolioRoute: PortfolioRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignalsRoute: SignalsRoute,
  StrategiesRoute: StrategiesRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiAlertsRoute: ApiAlertsRoute,
  ApiAutoBacktestRoute: ApiAutoBacktestRoute,
  ApiBotRoute: ApiBotRoute,
  ApiDerivSessionRoute: ApiDerivSessionRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLearningRoute: ApiLearningRoute,
  ApiNotesRoute: ApiNotesRoute,
  ApiPresenceRoute: ApiPresenceRoute,
  ApiPushRoute: ApiPushRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiStrategiesRoute: ApiStrategiesRoute,
  ApiTradesRoute: ApiTradesRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiAdminBotRoute: ApiAdminBotRoute,
  ApiAdminChangelogRoute: ApiAdminChangelogRoute,
  ApiAdminHealthRoute: ApiAdminHealthRoute,
  ApiAdminInvitesRoute: ApiAdminInvitesRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminUserConfigRoute: ApiAdminUserConfigRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthForgotPasswordRoute: ApiAuthForgotPasswordRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthResendVerificationRoute: ApiAuthResendVerificationRoute,
  ApiAuthResetPasswordRoute: ApiAuthResetPasswordRoute,
  ApiAuthVerifyEmailRoute: ApiAuthVerifyEmailRoute,
  ApiChatGroupsRoute: ApiChatGroupsRouteWithChildren,
  ApiChatMessagesRoute: ApiChatMessagesRoute,
  ApiChatReactionsRoute: ApiChatReactionsRoute,
  ApiChatTypingRoute: ApiChatTypingRoute,
  ApiChatUsersRoute: ApiChatUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
